server:
  http_listen_port: 8080

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /var/lib/mimir/data/mimir/tsdb

compactor:
  data_dir: /var/lib/mimir/data/mimir/compactor
  compaction_interval: 5m

ingester:
  wal:
    dir: /var/lib/mimir/data/mimir/wal
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    interface_names:
      - lo

distributor:
  ring:
    kvstore:
      store: inmemory

store_gateway:
  sharding_enabled: false

ruler:
  rule_path: /var/lib/mimir/data/mimir/rules
