package audio

import (
	"bytes"
	"fmt"
	"io"
	"reflect"

	"github.com/link00000000/fredboard/v3/internal/telemetry/logging"
)

const (
	connection_Unbounded = -1
	connectionType_In    = "in"
	connectionType_Out   = "out"
)

type InvalidConnectionConfigErr error

func newInvalidConnectionConfigErr(node Node, connectionType string, nMin, nMax, nActual int) InvalidConnectionConfigErr {
	sMin := fmt.Sprintf("%d", nMin)
	if nMin == connection_Unbounded {
		sMin = "UNBOUNDED"
	}

	sMax := fmt.Sprintf("%d", nMax)
	if nMax == connection_Unbounded {
		sMax = "UNBOUNDED"
	}

	return fmt.Errorf("invalid audio graph connection configuration. %s requires min=%s, max=%s \"%s\" connections, but got actual=%d", reflect.TypeOf(node).String(), sMin, sMax, connectionType, nActual)
}

// a unit that processess all input channels are writes to all output channels.
// once Start()ed, the node should not stop processing under any condition unless Stop() is called.
type Node interface {
	// process inputs and writing them to outputs
	// this function should block until all work is complete
	Tick(ins []io.Reader, outs []io.Writer)

	// gets the error generated by the last tick, if any
	Err() error
}

type Connection struct {
	bytes.Buffer

	from Node
	to   Node
}

type Graph struct {
	compositeNode *CompositeNode
}

func (graph *Graph) Tick() {
	graph.compositeNode.Tick([]io.Reader{}, []io.Writer{})
}

func (graph *Graph) AddNode(n Node) {
	graph.compositeNode.AddNode(n)
}

func (graph *Graph) RemoveNode(n Node) {
	graph.compositeNode.RemoveNode(n)
}

func (graph *Graph) CreateConnection(from, to Node) {
	graph.compositeNode.CreateConnection(from, to)
}

func (graph *Graph) RemoveConnection(from, to Node) {
	graph.compositeNode.RemoveConnection(from, to)
}

func NewGraph(logger *logging.Logger) *Graph {
	return &Graph{NewCompositeNode(logger)}
}
