package parallelgraph

import (
	"context"
	"fmt"
	"io"

	"accidentallycoded.com/fredboard/v3/internal/bytes"
	"accidentallycoded.com/fredboard/v3/internal/telemetry/logging"
)

type InvalidConnectionConfigErr error

func newInvalidConnectionConfigErr(nMin, nMax, nActual int) InvalidConnectionConfigErr {
	return fmt.Errorf("invalid audio graph connection configuration. node requires min=%d, max=%d, but got actual=%d", nMin, nMax, nActual)
}

type Node interface {
	// ins and outs will never be nil, but may be an empty slice.
	// this function should not block.
	Start(ctx context.Context, ins []io.Reader, outs []io.Writer) error

	// errors generated by the node.
	Errors() <-chan error

	// flush all data in the node out to the next node(s) in the graph
	// and close the error channel signifying that the node's work is complete.
	// this function should not block.
	FlushAndStop()
}

type Connection struct {
	bytes.ThreadsafeBuffer

	from Node
	to   Node
}

type Graph struct {
	*CompositeNode
}

func (graph *Graph) Start(ctx context.Context) error {
	return graph.CompositeNode.Start(ctx, []io.Reader{}, []io.Writer{})
}

func NewGraph(logger *logging.Logger) *Graph {
	return &Graph{NewCompositeNode(logger)}
}
