name: Build
on: [push]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - id: cache-pipenv
              uses: actions/cache@v1
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            - name: Install dependencies
              if: steps.cache-pipenv.outputs.cache-hit != 'true'
              run: |
                  pipenv install --deploy --dev

            - name: Build executable
              run: |
                  pipenv run build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  path: dist
                  name: fredboard-win-64

    release:
        runs-on: windows-latest
        needs: build
        if: startsWith(github.ref, 'refs/tags/v')

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                  path: dist
                  name: fredboard-win-64

            - id: tagName
              uses: olegtarasov/get-tag@v2.1

            - name: Create release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: latest
                  prerelease: false
                  title: "Fredboard ${{ steps.tagName.outputs.tag }}"
                  files: |
                      dist/*

