name: Fredboard Server

on:
  push:
    #branches: [main] enable when done testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: tagName
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Docker image'
        run: |
          docker build \
            --build-arg FREDBOARD_SERVER_VERSION=${{ steps.tagName.outputs.tag }} \
            --build-arg FREDBOARD_SERVER_COMMIT=${{ github.sha }} \
            --tag ghcr.io/link00000000/fredboard-server:latest \
            ${{ steps.tagName.outputs.tag ? ("--tag ghcr.io/link00000000/fredboard-server:" + steps.tagName.outputs.tag) : "" }}
            .

          docker push ghcr.io/link00000000/fredboard-server:latest
