name: Fredboard Server

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: tagName
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Docker image'
        run: |
          docker build \
            --build-arg FREDBOARD_VERSION_MAJOR=3 \
            --build-arg FREDBOARD_VERSION_MINOR=0 \
            --build-arg FREDBOARD_VERSION_PATCH=0 \
            --build-arg FREDBOARD_VERSION_COMMIT=${{ github.sha }} \
            --build-arg FREDBOARD_VERSION_DATE=$(date --iso-8601=seconds) \
            --tag ghcr.io/link00000000/fredboard-server:latest \
            --tag ghcr.io/link00000000/fredboard-server:${{ github.sha }} \
            .

          docker push ghcr.io/link00000000/fredboard-server:latest
